// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/mapreport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LongName               string                 `protobuf:"bytes,1,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	ShortName              string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Role                   int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	HwModel                int32                  `protobuf:"varint,4,opt,name=hw_model,json=hwModel,proto3" json:"hw_model,omitempty"`
	FirmwareVersion        string                 `protobuf:"bytes,5,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Region                 int32                  `protobuf:"varint,6,opt,name=region,proto3" json:"region,omitempty"`
	ModemPreset            int32                  `protobuf:"varint,7,opt,name=modem_preset,json=modemPreset,proto3" json:"modem_preset,omitempty"`
	HasDefaultChannel      bool                   `protobuf:"varint,8,opt,name=has_default_channel,json=hasDefaultChannel,proto3" json:"has_default_channel,omitempty"`
	LatitudeI              int32                  `protobuf:"fixed32,9,opt,name=latitude_i,json=latitudeI,proto3" json:"latitude_i,omitempty"`
	LongitudeI             int32                  `protobuf:"fixed32,10,opt,name=longitude_i,json=longitudeI,proto3" json:"longitude_i,omitempty"`
	Altitude               int32                  `protobuf:"varint,11,opt,name=altitude,proto3" json:"altitude,omitempty"`
	PositionPrecision      uint32                 `protobuf:"varint,12,opt,name=position_precision,json=positionPrecision,proto3" json:"position_precision,omitempty"`
	NumOnlineLocalNodes    uint32                 `protobuf:"varint,13,opt,name=num_online_local_nodes,json=numOnlineLocalNodes,proto3" json:"num_online_local_nodes,omitempty"`
	HasOptedReportLocation bool                   `protobuf:"varint,14,opt,name=has_opted_report_location,json=hasOptedReportLocation,proto3" json:"has_opted_report_location,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MapReport) Reset() {
	*x = MapReport{}
	mi := &file_internal_proto_mapreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReport) ProtoMessage() {}

func (x *MapReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mapreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReport.ProtoReflect.Descriptor instead.
func (*MapReport) Descriptor() ([]byte, []int) {
	return file_internal_proto_mapreport_proto_rawDescGZIP(), []int{0}
}

func (x *MapReport) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *MapReport) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *MapReport) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MapReport) GetHwModel() int32 {
	if x != nil {
		return x.HwModel
	}
	return 0
}

func (x *MapReport) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *MapReport) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

func (x *MapReport) GetModemPreset() int32 {
	if x != nil {
		return x.ModemPreset
	}
	return 0
}

func (x *MapReport) GetHasDefaultChannel() bool {
	if x != nil {
		return x.HasDefaultChannel
	}
	return false
}

func (x *MapReport) GetLatitudeI() int32 {
	if x != nil {
		return x.LatitudeI
	}
	return 0
}

func (x *MapReport) GetLongitudeI() int32 {
	if x != nil {
		return x.LongitudeI
	}
	return 0
}

func (x *MapReport) GetAltitude() int32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *MapReport) GetPositionPrecision() uint32 {
	if x != nil {
		return x.PositionPrecision
	}
	return 0
}

func (x *MapReport) GetNumOnlineLocalNodes() uint32 {
	if x != nil {
		return x.NumOnlineLocalNodes
	}
	return 0
}

func (x *MapReport) GetHasOptedReportLocation() bool {
	if x != nil {
		return x.HasOptedReportLocation
	}
	return false
}

var File_internal_proto_mapreport_proto protoreflect.FileDescriptor

const file_internal_proto_mapreport_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/mapreport.proto\x12\x05proto\"\x87\x04\n" +
	"\tMapReport\x12\x1b\n" +
	"\tlong_name\x18\x01 \x01(\tR\blongName\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x19\n" +
	"\bhw_model\x18\x04 \x01(\x05R\ahwModel\x12)\n" +
	"\x10firmware_version\x18\x05 \x01(\tR\x0ffirmwareVersion\x12\x16\n" +
	"\x06region\x18\x06 \x01(\x05R\x06region\x12!\n" +
	"\fmodem_preset\x18\a \x01(\x05R\vmodemPreset\x12.\n" +
	"\x13has_default_channel\x18\b \x01(\bR\x11hasDefaultChannel\x12\x1d\n" +
	"\n" +
	"latitude_i\x18\t \x01(\x0fR\tlatitudeI\x12\x1f\n" +
	"\vlongitude_i\x18\n" +
	" \x01(\x0fR\n" +
	"longitudeI\x12\x1a\n" +
	"\baltitude\x18\v \x01(\x05R\baltitude\x12-\n" +
	"\x12position_precision\x18\f \x01(\rR\x11positionPrecision\x123\n" +
	"\x16num_online_local_nodes\x18\r \x01(\rR\x13numOnlineLocalNodes\x129\n" +
	"\x19has_opted_report_location\x18\x0e \x01(\bR\x16hasOptedReportLocationB\x19Z\x17meshdump/internal/protob\x06proto3"

var (
	file_internal_proto_mapreport_proto_rawDescOnce sync.Once
	file_internal_proto_mapreport_proto_rawDescData []byte
)

func file_internal_proto_mapreport_proto_rawDescGZIP() []byte {
	file_internal_proto_mapreport_proto_rawDescOnce.Do(func() {
		file_internal_proto_mapreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_mapreport_proto_rawDesc), len(file_internal_proto_mapreport_proto_rawDesc)))
	})
	return file_internal_proto_mapreport_proto_rawDescData
}

var file_internal_proto_mapreport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_mapreport_proto_goTypes = []any{
	(*MapReport)(nil), // 0: proto.MapReport
}
var file_internal_proto_mapreport_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_mapreport_proto_init() }
func file_internal_proto_mapreport_proto_init() {
	if File_internal_proto_mapreport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_mapreport_proto_rawDesc), len(file_internal_proto_mapreport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_mapreport_proto_goTypes,
		DependencyIndexes: file_internal_proto_mapreport_proto_depIdxs,
		MessageInfos:      file_internal_proto_mapreport_proto_msgTypes,
	}.Build()
	File_internal_proto_mapreport_proto = out.File
	file_internal_proto_mapreport_proto_goTypes = nil
	file_internal_proto_mapreport_proto_depIdxs = nil
}
